### ISSUE TITLE
Summary table for individual service

### ISSUE THREAD

**Issue by amakhija** [vmware-tanzu/octant-plugin-for-knative#46]
Currently, when viewing details for an individual service, I see a detailed view of my PodTemplateSpec, Traffic Policies, Revisions, and Status. I should be able to see a summary view of my service on a separate Summary tab.

Design:
_Coming soon_

**Comment by AgruenVMware** [comment]
![Uploading Screen Shot 2020-10-12 at 1.50.31 PM.png…]()

**Comment by AgruenVMware** [comment]
![Screen Shot 2020-10-14 at 1 37 00 PM](https://user-images.githubusercontent.com/68018740/96030988-5c96dd80-0e22-11eb-931f-d89f0d56dadd.png)

**Comment by scothis** [comment]
Likes:
- labeling the latest ready and created revisions (although it's a bit awkward with Octant's component model)
- showing actual/desired scale for each revision

Interestings:
- showing the traffic needs to be approached carefully. A particular revision could receive traffic from multiple routes. Do we only show the traffic for the Service's Route? If we're viewing this same listing from the context of a Configuration there is no single Route, so show all routes or nothing?

Nits:
- it's more typical to show the "Created" date as an "Age" with the value as a duration (4m28s) rather than a static timestamp
- status is typically summarized into a traffic light indicator next to the name

**Comment by scothis** [comment]
as implemented

<img width="985" alt="Screen Shot 2020-10-16 at 11 14 22 AM" src="https://user-images.githubusercontent.com/302992/96276314-cccb6d80-0fa0-11eb-8507-1238be8cd880.png">

The "Route Traffic" column shows all traffic rules for all route sending traffic to the revision. Linking to the Route defining the traffic rule. The total percentage of traffic does not need to sum to 100% as Routes can send traffic to Revisions managed by different Configurations.
